### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by tatanabs** [isaackogan/TikTokLive#185] opened 2024-02-25 23:08 UTC
### Describe the bug

`...`I just copy/pasted the example code to do a test
and it doesn't work,

### code

`
from TikTokLive.client.client import TikTokLiveClient
from TikTokLive.client.logger import LogLevel
from TikTokLive.events import ConnectEvent, GiftEvent

client: TikTokLiveClient = TikTokLiveClient(
    unique_id="@boost_club"
)

@client.on(ConnectEvent)
async def on_connect(event: ConnectEvent):
    client.logger.info(f"Connected to @{event.unique_id}!")

@client.on(GiftEvent)
async def on_comment(event: GiftEvent):
    client.logger.info("Received a gift!")

    # Can have a streak and streak is over
    if event.gift.streakable and not event.streaking:
        print(f"{event.user.unique_id} sent {event.gift.count}x \"{event.gift.info.name}\"")

    # Cannot have a streak
    elif not event.gift.streakable:
        print(f"{event.user.unique_id} sent \"{event.gift.info.name}\"")

if __name__ == '__main__':
    # Enable debug info
    client.logger.setLevel(LogLevel.INFO.value)

    # Connect
    client.run()`

### Actual Behaviour
*error

`[TikTokLive] INFO from newtest.py:15 — Connected to @boost_club!
Traceback (most recent call last):
  File "/home/akeem/Documents/Python/newtest.py", line 36, in <module>
    client.run()
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/TikTokLive/client/client.py", line 170, in run
    return self._asyncio_loop.run_until_complete(self.connect(**kwargs))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/TikTokLive/client/client.py", line 155, in connect
    await task
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/TikTokLive/client/client.py", line 203, in _client_loop
    async for event in self._ws_loop(initial_response):
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/TikTokLive/client/client.py", line 237, in _ws_loop
    for event in self._parse_webcast_response(webcast_message):
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/TikTokLive/client/client.py", line 322, in _parse_webcast_response
    proto_event: ProtoEvent = event_type().parse(response.payload)
  File "<string>", line 16, in __init__
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 631, in __post_init__
    for field_name, meta in self._betterproto.meta_by_field_name.items():
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 698, in __getattribute__
    value = super().__getattribute__(name)
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 754, in _betterproto
    meta = ProtoClassMetadata(self.__class__)
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 568, in __init__
    self.default_gen = self._get_default_gen(cls, fields)
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 575, in _get_default_gen
    return {field.name: cls._get_field_default_gen(field) for field in fields}
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 575, in <dictcomp>
    return {field.name: cls._get_field_default_gen(field) for field in fields}
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/betterproto/__init__.py", line 910, in _get_field_default_gen
    elif issubclass(t, Enum):
TypeError: issubclass() arg 1 must be a class
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<WebSocketCommonProtocol.transfer_data() running at /home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py:963> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb9579d0fa0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fb9579d0f40>()]>
Task was destroyed but it is pending!
task: <Task pending name='Task-8' coro=<WebSocketCommonProtocol.keepalive_ping() running at /home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py:1254> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb9579d0f10>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<WebSocketCommonProtocol.close_connection() running at /home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py:1301> wait_for=<Task pending name='Task-7' coro=<WebSocketCommonProtocol.transfer_data() running at /home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py:963> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb9579d0fa0>()]> cb=[<TaskWakeupMethWrapper object at 0x7fb9579d0f40>()]>>
Exception ignored in: <coroutine object WebSocketCommonProtocol.close_connection at 0x7fb9579c7340>
Traceback (most recent call last):
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1337, in close_connection
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1355, in close_transport
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/protocol.py", line 1379, in wait_for_connection_lost
  File "/home/akeem/Documents/Python/venv/lib/python3.8/site-packages/websockets/legacy/async_timeout.py", line 74, in timeout
RuntimeError: no running event loop
`

### Package Version

My version of TikTokLive is `6.0.1

### Operating System

- [ ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

**Comment by newbie-hue** [comment] 2024-02-27 05:54
me too.

**Comment by isaackogan** [comment] 2024-02-28 19:15
Closed as duplicate of https://github.com/isaackogan/TikTokLive/issues/183

**Closed by isaackogan** 2024-02-28 19:15 UTC
