### ISSUE TITLE
the gift urls are not shown or are None

### ISSUE THREAD

**Issue by joachimschwarzschild** [isaackogan/TikTokLive#9] opened 2022-03-05 23:09 UTC
Hi Isaac,

i tried to display the gift image urls but it is showing None
then i tried to add a print in your base.py then it showed me them

`async def __fetch_available_gifts(self) -> Optional[Dict[int, ExtendedGift]]:
        """
        Fetch available gifts from Webcast API
        :return: Gift info dict

        """

        try:
            response = await self._http.get_json_object_from_webcast_api("gift/list/", self._client_params)
            # print(f"GIFT RESPONSE: {response}"  )
            print("##########################################################################################")
            if response and 'gifts' in response and response['gifts'] and len(response['gifts']) > 0: 
                for gift in response['gifts']:
                    print(f"NAME: {gift['describe']} | DIAMONDS: {gift['diamond_count']} | URL LIST: {gift['image']['url_list']}")
                    # print(f"NAME: {gift}")
            else:
                print("gift error")
            gifts: Optional[List] = response.get("gifts")

            if isinstance(gifts, list):
                for gift in gifts:
                    try:
                        _gift: ExtendedGift = from_dict(ExtendedGift, gift)
                        self.__available_gifts[_gift.id] = _gift
                    except:
                        logging.error(traceback.format_exc() + "\nFailed to parse gift's extra info")

            return self.__available_gifts
        except Exception as err:
            logging.error(traceback.format_exc() + "\nFailed to retrieve gifts from webcast api")
            print(f"ERROR: {err}")
            return None`
            
   maybe you could fix it in the next ersion or i could also fix it if you want
   
   i will attach a file with the output i wanted and got after i set my own prints 
   
![gift_urls](https://user-images.githubusercontent.com/22036339/156902712-fa9a72f4-c686-49d1-8602-0704f4c90a59.png)

**Comment by joachimschwarzschild** [comment] 2022-03-05 23:10
by the way my discord is pryton#8919 if you want to contact me

**Comment by isaackogan** [comment] 2022-03-06 02:23
I'm having difficulty parsing this.

Can you explain more in depth what is wrong?

**Comment by joachimschwarzschild** [comment] 2022-03-06 10:30
basically if i want to get all availible gifts it gets them via your api but they dont contains the urls to the images of the gifts 
can you reproduce that or am i doing something wrong?

**Comment by isaackogan** [comment] 2022-03-07 21:46
I can't reproduce that on my end, no. They should be there within the extended_gift attribute. If that attribute is not provided, you likely have that config option disabled in the constructor of the TikTokLiveClient object.

**Comment by isaackogan** [comment] 2022-03-07 21:48
> I can't reproduce that on my end, no. They should be there within the extended_gift attribute. If that attribute is not provided, you likely have that config option disabled in the constructor of the TikTokLiveClient object.

Nevermind, reproducable

**Comment by isaackogan** [comment] 2022-03-07 21:58
Issue fixed, will be released in next version https://github.com/isaackogan/TikTokLive/issues/10 pending checklist completion

**Closed by isaackogan** 2022-03-07 21:58 UTC
Labels: bug
