### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by KalvinThien** [isaackogan/TikTokLive#191] opened 2024-03-05 14:54 UTC
### Describe the bug

` C:/Users/KalvinThien/AppData/Local/Programs/Python/Python311/python.exe d:/tech_review/edit_video/Ewrite/Full_web/pages/Etool_source/Full_Code_Etools/tiktoklivedownload/main.py
[TikTokLive] INFO from d:\tech_review\edit_video\Ewrite\Full_web\pages\Etool_source\Full_Code_Etools\tiktoklivedownload\main.py:14 — Connected!
[TikTokLive] INFO from C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\TikTokLive\client\web\routes\fetch_video.py:123 — Attempting to start download on stream for 'phamngoclinh_official'.
[TikTokLive] INFO from C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\TikTokLive\client\web\routes\fetch_video.py:152 — Started the download to path "phamngoclinh_official.mp4" for duration "infinite" seconds on user @phamngoclinh_official with video quality "LD".
[TikTokLive] INFO from d:\tech_review\edit_video\Ewrite\Full_web\pages\Etool_source\Full_Code_Etools\tiktoklivedownload\main.py:33 — Disconnected!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\TikTokLive\client\web\routes\fetch_video.py", line 198, in _threaded_recording
    self._ffmpeg.run()
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\site-packages\ffmpy.py", line 113, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -loglevel error -y -i https://pull-f5-sg01.tiktokcdn.com/stage/stream-2420575215836201029_ld.flv?expire=1710859644&sign=f951adcfee7b172d3b0271b38dcf3e9d phamngoclinh_official.mp4 -f mp4` exited with status 15

STDOUT:

STDERR:

Cancelling an overlapped future failed
future: <_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>
Traceback (most recent call last):
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] The handle is invalid
Cancelling an overlapped future failed
future: <_OverlappedFuture pending cb=[_ProactorReadPipeTransport._loop_reading()]>
Traceback (most recent call last):
  File "C:\Users\KalvinThien\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 71, in _cancel_overlapped
    self._ov.cancel()
OSError: [WinError 6] The handle is invalid
PS D:\tech_review\edit_video\Ewrite\Full_web\pages\Etool_source\Full_Code_Etools\tiktoklivedownload> `

### Expected Behaviour

`...`

### Actual Behaviour
*If applicable, include screenshots!*

`...`

### Package Version

My version of TikTokLive is `6.0.2post1`.

### Operating System

- [ ] Windows 11

### Anything Else

If there's anything else, add it here.

I use the example code at Link https://github.com/isaackogan/TikTokLive/blob/master/examples/recording.py

I use Python version 3.11.6 
FFmpeg Newest

 
![image](https://github.com/isaackogan/TikTokLive/assets/120565705/620788af-e4fc-4fe6-817c-cb8db445245b)

**Comment by isaackogan** [comment] 2024-03-07 05:54
This looks like an issue with FFmpeg on Windows. 

See https://github.com/Zulko/moviepy/issues/1749. 

TikTokLive is only tested on MacOS & Linux, and we don't directly support Windows. If there is a fix for this issue that you can find, I will gladly accept a PR for it, but I will not be able to reproduce & fix it on my own.

**Closed by isaackogan** 2024-03-07 05:54 UTC
