### ISSUE TITLE
Age restricted stream despite session_id

### ISSUE THREAD

**Issue by int3debug** [isaackogan/TikTokLive#256] opened 2024-09-14 06:04 UTC
### Describe the bug
After updating from version 6.0.8 to newest version my program no longer works

Bug:
[ERROR] Unexpected error: Age restricted stream. Cannot fetch room info. Pass sessionid to log in & bypass age restriction.. Retrying in 10 seconds...

I use:
client.web.set_session_id("SESSION_ID")

### Expected Behaviour

Should still work

### Actual Behaviour
*If applicable, include screenshots!*

> python app.py -u 'USERNAME' -r
[INFO] USERNAME is live!
[ERROR] Unexpected error: Age restricted stream. Cannot fetch room info. Pass sessionid to log in & bypass age restriction.. Retrying in 10 seconds...

### Package Version

My version of TikTokLive is `TikTokLive-6.1.3`.

### Operating System

- [ ] Windows
- [ x] Linux
- [ ] MacOS
- [ ] Other (Specifically, `...`)

### Anything Else

If there's anything else, add it here.

Here is proof:

TikTokLive-6.0.8

> python app.py -u 'USERNAME' -r
[INFO] USERNAME is live!
[INFO] USERNAME connected

Successfully installed TikTokLive-6.1.3

> python app.py -u 'USERNAME' -r
Traceback (most recent call last):
  File "app.py", line 20, in <module>
    from TikTokLive.client.web.routes.fetch_video import VideoFetchQuality, VideoFetchFormat
ModuleNotFoundError: No module named 'TikTokLive.client.web.routes.fetch_video'

> sed -i 's/fetch_video/download_video/g' app.py

> python app.py -u 'USERNAME' -r
[INFO] USERNAME is live!
[ERROR] Unexpected error: Age restricted stream. Cannot fetch room info. Pass sessionid to log in & bypass age restriction.. Retrying in 10 seconds...

Successfully installed TikTokLive-6.0.8

> sed -i 's/download_video/fetch_video/g' app.py
> python app.py -u 'USERNAME' -r
2024-09-14 07:51:10,667 [INFO] USERNAME is live!
2024-09-14 07:51:15,262 [INFO] USERNAME connected

Unfortunately the problem still exists @isaackogan

**Comment by isaackogan** [comment] 2024-09-14 21:33
I can't reproduce this...

**Comment by MissZeda** [comment] 2024-09-16 08:40
After my attempts, I discovered that the issue was due to the IP being blocked by TikTok. Similar to Google's CAPTCHA, when I used a residential proxy, I no longer encountered the age restriction issue.

**Comment by isaackogan** [comment] 2024-09-19 03:03
Most likely fixed in https://github.com/isaackogan/TikTokLive/commit/1c95a74bdeb470f30ca39157eef76883a2d36b55

Please confirm so I can close this issue. Thanks!

@MissZeda @int3debug

**Comment by isaackogan** [comment] 2024-09-19 15:29
Possibly fixed in https://github.com/isaackogan/TikTokLive/commit/f7632924d75f029c3d8d251c6d5c3daf3ef2e958, please confirm so I can close thanks.

@int3debug

**Comment by isaackogan** [comment] 2024-09-19 15:40
Confirmed fixed in https://github.com/isaackogan/TikTokLive/issues/260

**Closed by isaackogan** 2024-09-19 15:40 UTC
